services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - mobility-application
    profiles: [frontend]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongo_mobility:27017/mydatabase
    depends_on:
      - mongo_mobility
    networks:
      - mobility-application

  mongo_mobility:
    image: mongo:6
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mobility-application

networks:
  mobility-application:
    name: mobility-application
    driver: bridge

volumes:
  mongodb-data:
